export default {
    GET_PRODUCTS: 'PRODUCTS_GET_PRODUCTS',
    GET_PRODUCTS_SUCCESS: 'PRODUCTS_GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_ERROR: 'PRODUCTS_GET_PRODUCTS_ERROR',
    SEARCH_PRODUCT: 'PRODUCTS_SEARCH_PRODUCT',
};